refresh_rate: 3 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} - {m}{n}"
  requests:
    kind: file
    path: "logs/log.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} - {m}{n}"
root:
  level: info
  appenders:
    - stdout
    - requests
