version: '3.7'

networks:
  default:

volumes:
  redis:
  letsencrypt:

services:
  nginx:
    image: walletconnect-service/nginx:main
    deploy:
      mode: global
    # This port format is needed to get real ip address of the client
    environment:
      DOMAIN_URL: wctest.ankr.com
      EMAIL: gooomoon86@gmail.com
      CONTAINER_NAME: bridge
      APP_PORT: 5200
      APP_QTY: 2
    depends_on:
      - bridge0
      - bridge1
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      - letsencrypt:/etc/letsencrypt

  redis:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    volumes:
      - redis:/data

  bridge0:
    image: walletconnect-service/bridge:main
    environment:
      REDIS_URL: redis://redis:6379/0
    deploy:
      resources:
        limits:
          memory: 1G

  bridge1:
    image: walletconnect-service/bridge:main
    environment:
      REDIS_URL: redis://redis:6379/0
    deploy:
      resources:
        limits:
          memory: 1G
