version: '3.7'

networks:
  default:

volumes:
  redis:
  letsencrypt:

services:
  nginx:
    image: NGINX_IMAGE
    deploy:
      mode: global
    # This port format is needed to get real ip address of the client
    environment:
      DOMAIN_URL: BRIDGE_URL
      EMAIL: CERTBOT_EMAIL
      CONTAINER_NAME: bridge
      APP_PORT: 5200
      APP_QTY: 2
    depends_on:
      - bridge0
      - bridge1
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      - letsencrypt:/etc/letsencrypt

  redis:
    image: REDIS_IMAGE
    volumes:
      - redis:/data

  bridge0:
    image: BRIDGE_IMAGE
    environment:
      REDIS_URL: redis://redis:6379/0
    deploy:
      resources:
        limits:
          memory: 1G

  bridge1:
    image: BRIDGE_IMAGE
    environment:
      REDIS_URL: redis://redis:6379/0
    deploy:
      resources:
        limits:
          memory: 1G
